"""added products and orders model

Revision ID: 7d89aa3dff63
Revises: 58ce23896376
Create Date: 2023-02-13 05:51:26.058465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d89aa3dff63'
down_revision = '58ce23896376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('product_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('discount_name', sa.String(length=100), nullable=False),
    sa.Column('discount_description', sa.String(length=1000), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('discount_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('product_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=True),
    sa.Column('product_discount_id', sa.Integer(), nullable=True),
    sa.Column('product_inventory_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_image_url', sa.String(length=256), nullable=False),
    sa.Column('product_dimensions', sa.String(length=256), nullable=False),
    sa.Column('product_brand', sa.String(length=100), nullable=False),
    sa.Column('product_weight', sa.String(length=100), nullable=False),
    sa.Column('product_price', sa.String(length=100), nullable=False),
    sa.Column('product_description', sa.String(length=1000), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['product_discount_id'], ['product_discount.id'], ),
    sa.ForeignKeyConstraint(['product_inventory_id'], ['product_inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('payment_details_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.ForeignKeyConstraint(['payment_details_id'], ['payment_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint(None, ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id')

    op.drop_table('order')
    op.drop_table('order_item')
    op.drop_table('product')
    op.drop_table('product_inventory')
    op.drop_table('product_discount')
    op.drop_table('product_category')
    op.drop_table('payment_details')
    # ### end Alembic commands ###
