"""added subscription model

Revision ID: ac96d5930472
Revises: 0184c7d4d9e6
Create Date: 2023-02-24 10:31:22.808197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac96d5930472'
down_revision = '0184c7d4d9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription', sa.String(length=50), nullable=False),
    sa.Column('generation_count', sa.Integer(), nullable=False),
    sa.Column('number_of_images', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=256), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('account')
    # ### end Alembic commands ###
